### ISSUE TITLE
Wrong type for ticket in MessageSendResponse

### ISSUE THREAD

**Issue by kopax** [smsfactor/smsfactor-java-sdk#1]
According to the documentation here https://dev.smsfactor.com/en/api/sms/send/send-single

It seems that the correct type for ticket is `String`.

https://github.com/smsfactor/smsfactor-java-sdk/blob/f79c5f7e6c2c0cb6a4da7cd0bc05b67aeef2e1ce/src/main/java/com/smsfactor/response/MessageSendResponse.java#L5

Where is the mistake?

**Comment by fpalamour** [comment]
Thank you @kopax  for your contribution ! Let us know if you have any question about our API at support@smsfactor.com. Cheers.
